#15 Add item requests
Noskovsk/java-shareit pull request #3
Opened 2022-11-19 19:13 UTC by Noskovsk

2022-11-24 06:59 UTC, Frilock requested changes
Добрый день, по работе не увидел таких пунктов из ТЗ:

Реализованы тесты для слоя репозиториев приложения с использованием аннотации @DataJpaTest. Работа с аннотацией @DataJpaTest не рассматривалась подробно в уроке, студенты учат самостоятельно.

Реализованы тесты для работы с JSON для DTO в вашем приложении с помощью аннотации @JsonTest. Такие тесты имеют смысл в тех случаях, когда DTO содержат в себе некоторую логику.

Кроме того, во многих тестах отсутствуют модификаторы доступа для полей классов.

2022-11-24 06:59 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Entity(name = "requests")
А аннотация Table Вам не нужна? Обычно как то так используется
@Entity
@Table(name = "cat_table")

2022-11-24 06:59 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users
Строчку лучше пропустить, чтобы не сливалось

2022-11-24 06:59 UTC, Frilock commented on src/test/java/ru/practicum/shareit/PaginationParamsTest.java
> +        assertNotNull(throwable.getMessage());
Лучше конечно  конкретное сообщение проверять, через contains, чтобы точно быть уверенным, что эта точно ошибка которую вы ждете

2022-11-24 06:59 UTC, Frilock commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    ObjectMapper mapper = new ObjectMapper();
Модификаторы приватные добавьте, а маппер вроде final можно сделать

2022-11-27 12:18 UTC, Noskovsk commented on src/test/java/ru/practicum/shareit/controller/BookingControllerTest.java
> +    ObjectMapper mapper = new ObjectMapper();
Исправил

2022-11-27 12:20 UTC, Noskovsk commented on src/test/java/ru/practicum/shareit/PaginationParamsTest.java
> +        assertNotNull(throwable.getMessage());
Исправил

2022-11-27 12:25 UTC, Noskovsk commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Entity(name = "requests")
Переделал. Но руководствовался статьей: https://www.baeldung.com/jpa-entities
_If we don't use the @Table annotation, the name of the table will be the name of the entity._

2022-11-27 15:58 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +@Entity(name = "requests")
Да все верно, это как с аннотацией Column, которую можно не ставить если колонка в БД также называется. Но вот почему то в своей практике сложилось, что лучше я аннотацию Column и Table поставлю - там же еще различные параметры есть, например, схема для таблицы или размерность полей, и прочие флаги для колонки

2022-11-27 15:58 UTC, Frilock approved these changes
Принято, в целом все ок.

2022-12-01 04:25 UTC, merged